 # Generated by Django 4.2.3 on 2023-08-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('inv_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='invoicedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unitprice', models.DecimalField(decimal_places=3, default=10, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_api.invoice')),
            ],
        ),
    ]
