# Generated by Django 4.2.3 on 2023-08-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='unitprice',
            field=models.IntegerField(),
        ),
    ]
