# Generated by Django 4.2.3 on 2023-08-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_api', '0002_alter_invoicedetail_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='unitprice',
        ),
    ]
