# Generated by Django 4.2.3 on 2023-08-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_api', '0003_remove_invoicedetail_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='inv',
        ),
    ]
