# Generated by Django 4.2.3 on 2023-08-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_api', '0005_invoicedetail_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicedetail', to='inv_api.invoice'),
        ),
    ]
