# Generated by Django 4.2.3 on 2023-08-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_api', '0007_alter_invoicedetail_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='inv_api.invoice'),
        ),
    ]
