# Generated by Django 4.2.3 on 2023-08-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_api', '0009_invoicedetail_price_invoicedetail_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='price',
        ),
    ]
